# Generated by Django 5.1.15 on 2026-08-27 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField(max_length=1000)),
                ("robots_txt_allowed", models.BooleanField(default=True)),
                (
                    "crawl_delay",
                    models.FloatField(
                        default=2.0, help_text="Seconds between requests"
                    ),
                ),
                ("max_concurrent", models.IntegerField(default=2)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "websites",
                "ordering": ["-created_at"],
            },
        ),
    ]
