# Generated by Django 5.1.15 on 2026-08-27 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("scraping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("target_url", models.URLField(max_length=2000)),
                (
                    "render_mode",
                    models.CharField(
                        choices=[
                            ("static", "Statique (HTTP)"),
                            ("javascript", "JavaScript (Playwright)"),
                        ],
                        default="static",
                        max_length=12,
                    ),
                ),
                (
                    "wait_for_selector",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "pagination_selector",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("max_pages", models.IntegerField(default=1)),
                ("request_delay", models.FloatField(default=2.0)),
                ("is_active", models.BooleanField(default=True)),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_configs",
                        to="projects.project",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_configs",
                        to="scraping.website",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_configs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("pages_scraped", models.IntegerField(default=0)),
                ("rows_extracted", models.IntegerField(default=0)),
                ("rows_valid", models.IntegerField(default=0)),
                ("rows_invalid", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="extraction.extractionconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_jobs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Toutes les heures"),
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("custom", "Personnalisé (cron)"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_jobs",
                        to="extraction.extractionconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Selector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "selector_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("number", "Nombre"),
                            ("price", "Prix"),
                            ("date", "Date"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("phone", "Téléphone"),
                            ("boolean", "Booléen"),
                            ("html", "HTML brut"),
                            ("image", "Image"),
                            ("json", "JSON"),
                            ("list", "Liste"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("css", "CSS Selector"),
                            ("xpath", "XPath"),
                            ("regex", "Regex"),
                        ],
                        default="css",
                        max_length=5,
                    ),
                ),
                ("selector_value", models.CharField(max_length=1000)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "transformation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python expression for data transformation",
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTML attribute to extract (href, src, etc.)",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selectors",
                        to="extraction.extractionconfig",
                    ),
                ),
            ],
            options={
                "db_table": "selectors",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionConfigVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict, help_text="Full config snapshot at this version"
                    ),
                ),
                ("change_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="extraction.extractionconfig",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_config_versions",
                "ordering": ["-version_number"],
                "unique_together": {("config", "version_number")},
            },
        ),
    ]
