# Generated by Django 5.1.15 on 2026-08-27 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ECOMMERCE", "E-commerce"),
                            ("DIRECTORY", "Annuaire"),
                            ("JOB_BOARD", "Offres d'emploi"),
                            ("NEWS", "Actualités"),
                            ("GENERAL", "Général"),
                            ("TIPS", "Astuces"),
                            ("WARNINGS", "Pièges"),
                        ],
                        default="GENERAL",
                        max_length=15,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_articles",
                "ordering": ["-updated_at"],
            },
        ),
    ]
