# Generated by Django 5.1.15 on 2026-08-27 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "completeness",
                    models.FloatField(
                        default=0.0, help_text="0-100: % of fields filled"
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        default=0.0, help_text="0-100: % of accurate values"
                    ),
                ),
                (
                    "consistency",
                    models.FloatField(
                        default=0.0, help_text="0-100: format consistency"
                    ),
                ),
                (
                    "uniqueness",
                    models.FloatField(default=0.0, help_text="0-100: % unique records"),
                ),
                (
                    "validity",
                    models.FloatField(
                        default=0.0, help_text="0-100: % valid format values"
                    ),
                ),
                (
                    "global_score",
                    models.FloatField(default=0.0, help_text="Weighted average /100"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_report",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "quality_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("MISSING_VALUE", "Valeur manquante"),
                            ("INCONSISTENT_PRICE", "Prix incohérent"),
                            ("INVALID_FORMAT", "Format invalide"),
                            ("INVALID_URL", "URL invalide"),
                            ("INVALID_EMAIL", "Email invalide"),
                            ("DUPLICATE", "Doublon"),
                            ("OUTLIER", "Valeur aberrante"),
                            ("EMPTY_RECORD", "Enregistrement vide"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("suggestion", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="datasets.datarecord",
                    ),
                ),
            ],
            options={
                "db_table": "anomalies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset", "anomaly_type"],
                        name="anomalies_dataset_1534da_idx",
                    ),
                    models.Index(
                        fields=["is_resolved"], name="anomalies_is_reso_33ebf7_idx"
                    ),
                ],
            },
        ),
    ]
