# Generated by Django 5.1.15 on 2026-08-27 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("analyze_page", "Analyse de page"),
                            ("structure_data", "Structuration"),
                            ("clean_data", "Nettoyage"),
                            ("quality_check", "Contrôle qualité"),
                            ("anomaly_detect", "Détection anomalies"),
                            ("generate_schema", "Génération schéma"),
                            ("chat", "Chat assistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(max_length=255)),
                ("prompt_content", models.TextField()),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_response", models.TextField()),
                ("parsed_data", models.JSONField(default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "Haute (>=90%)"),
                            ("MEDIUM", "Moyenne (70-89%)"),
                            ("LOW", "Faible (<70%)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="ai_engine.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_responses",
                "ordering": ["-created_at"],
            },
        ),
    ]
